# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Modules"
  url = "#modules"
  weight = 20


[[main]]
  name = "Logistics"
  url = "#logistics"
  weight = 30

# [[main]]
#   name = "Schedule"
#   url = "#schedule"
#   weight = 20

[[main]]
  name = "People"
  url = "#people"
  weight = 40

[[main]]
name = "Syllabus"
url = "courses/syllabus/"
weight = 50
  
[[main]]
  name = "Schedule"
  url = "https://docs.google.com/spreadsheets/d/19O7z95We0cv8INWuARNzUI_iYVASlbBOprEPl3pO0kw/edit?usp=sharing"
 weight = 60


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
